services:
  argent-vpn-service:
    build: .
    ports:
      - "8003:8000"
    restart: always
    env_file: .env
    environment:
      - PYTHONPATH=/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - argent-shared-network

networks:
  argent-shared-network:
    external: true